CREATE TABLE [dbo].[player_attributes] (
    [id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    [player_id] UNIQUEIDENTIFIER NOT NULL UNIQUE,
    [ball_control] INT NULL,
    [crossing] INT NULL,
    [weak_foot] INT NULL,
    [dribbling] INT NULL,
    [finishing] INT NULL,
    [free_kick] INT NULL,
    [heading] INT NULL,
    [long_passing] INT NULL,
    [long_shot] INT NULL,
    [penalties] INT NULL,
    [short_passing] INT NULL,
    [shot_power] INT NULL,
    [sliding_tackle] INT NULL,
    [standing_tackle] INT NULL,
    [volleys] INT NULL,
    [acceleration] INT NULL,
    [agility] INT NULL,
    [balance] INT NULL,
    [jumping] INT NULL,
    [pace] INT NULL,
    [reactions] INT NULL,
    [sprint_speed] INT NULL,
    [stamina] INT NULL,
    [strength] INT NULL,
    [aggression] INT NULL,
    [attacking_position] INT NULL,
    [awareness] INT NULL,
    [communication] INT NULL,
    [composure] INT NULL,
    [defensive_positioning] INT NULL,
    [interceptions] INT NULL,
    [marking] INT NULL,
    [positivity] INT NULL,
    [positioning] INT NULL,
    [vision] INT NULL,
    [updated_at] DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT [FK_player_attributes_players] FOREIGN KEY ([player_id]) REFERENCES [dbo].[players]([id]) ON DELETE CASCADE
);
GO

CREATE INDEX [IX_player_attributes_player_id] ON [dbo].[player_attributes]([player_id]);
GO
