// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OurGame.Persistence.Models;

public partial class AgeGroupCoordinator
{
    public Guid Id { get; set; }

    public Guid AgeGroupId { get; set; }

    public Guid CoachId { get; set; }

    public virtual AgeGroup AgeGroup { get; set; }

    public virtual Coach Coach { get; set; }
}