// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OurGame.Persistence.Models;

public partial class AppliedTemplate
{
    public Guid Id { get; set; }

    public Guid SessionId { get; set; }

    public Guid TemplateId { get; set; }

    public DateTime AppliedAt { get; set; }

    public virtual TrainingSession Session { get; set; }

    public virtual DrillTemplate Template { get; set; }
}