// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OurGame.Persistence.Models;

public partial class AttributeEvaluation
{
    public Guid Id { get; set; }

    public Guid PlayerId { get; set; }

    public Guid EvaluatedBy { get; set; }

    public DateTime EvaluatedAt { get; set; }

    public int? OverallRating { get; set; }

    public string CoachNotes { get; set; }

    public DateOnly? PeriodStart { get; set; }

    public DateOnly? PeriodEnd { get; set; }

    public virtual Coach EvaluatedByNavigation { get; set; }

    public virtual ICollection<EvaluationAttribute> EvaluationAttributes { get; set; } = new List<EvaluationAttribute>();

    public virtual Player Player { get; set; }
}