// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OurGame.Persistence.Models;

public partial class EmergencyContact
{
    public Guid Id { get; set; }

    public Guid PlayerId { get; set; }

    public string Name { get; set; }

    public string Phone { get; set; }

    public string Relationship { get; set; }

    public bool IsPrimary { get; set; }

    public virtual Player Player { get; set; }
}