// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OurGame.Persistence.Models;

public partial class EvaluationAttribute
{
    public Guid Id { get; set; }

    public Guid EvaluationId { get; set; }

    public string AttributeName { get; set; }

    public int? Rating { get; set; }

    public string Notes { get; set; }

    public virtual AttributeEvaluation Evaluation { get; set; }
}