// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OurGame.Persistence.Models;

public partial class FormationPosition
{
    public Guid Id { get; set; }

    public Guid FormationId { get; set; }

    public string Position { get; set; }

    public decimal? XCoord { get; set; }

    public decimal? YCoord { get; set; }

    public string Direction { get; set; }

    public int PositionIndex { get; set; }

    public virtual Formation Formation { get; set; }
}