// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OurGame.Persistence.Models;

public partial class LineupPlayer
{
    public Guid Id { get; set; }

    public Guid LineupId { get; set; }

    public Guid PlayerId { get; set; }

    public string Position { get; set; }

    public int? SquadNumber { get; set; }

    public bool IsStarting { get; set; }

    public virtual MatchLineup Lineup { get; set; }

    public virtual Player Player { get; set; }
}