// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OurGame.Persistence.Models;

public partial class MatchSubstitution
{
    public Guid Id { get; set; }

    public Guid MatchId { get; set; }

    public int Minute { get; set; }

    public Guid PlayerOutId { get; set; }

    public Guid PlayerInId { get; set; }

    public virtual Match Match { get; set; }

    public virtual Player PlayerIn { get; set; }

    public virtual Player PlayerOut { get; set; }
}