// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OurGame.Persistence.Models;

public partial class MatchCoach
{
    public Guid Id { get; set; }

    public Guid MatchId { get; set; }

    public Guid CoachId { get; set; }

    public virtual Coach Coach { get; set; }

    public virtual Match Match { get; set; }
}