// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace OurGame.Persistence.Models;

public partial class OurGameContext : DbContext
{
    public OurGameContext(DbContextOptions<OurGameContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AgeGroup> AgeGroups { get; set; }

    public virtual DbSet<AgeGroupCoordinator> AgeGroupCoordinators { get; set; }

    public virtual DbSet<AppliedTemplate> AppliedTemplates { get; set; }

    public virtual DbSet<AttributeEvaluation> AttributeEvaluations { get; set; }

    public virtual DbSet<Card> Cards { get; set; }

    public virtual DbSet<Club> Clubs { get; set; }

    public virtual DbSet<Coach> Coaches { get; set; }

    public virtual DbSet<DevelopmentGoal> DevelopmentGoals { get; set; }

    public virtual DbSet<DevelopmentPlan> DevelopmentPlans { get; set; }

    public virtual DbSet<Drill> Drills { get; set; }

    public virtual DbSet<DrillLink> DrillLinks { get; set; }

    public virtual DbSet<DrillTemplate> DrillTemplates { get; set; }

    public virtual DbSet<EmergencyContact> EmergencyContacts { get; set; }

    public virtual DbSet<EvaluationAttribute> EvaluationAttributes { get; set; }

    public virtual DbSet<Formation> Formations { get; set; }

    public virtual DbSet<FormationPosition> FormationPositions { get; set; }

    public virtual DbSet<Goal> Goals { get; set; }

    public virtual DbSet<Injury> Injuries { get; set; }

    public virtual DbSet<Kit> Kits { get; set; }

    public virtual DbSet<KitOrder> KitOrders { get; set; }

    public virtual DbSet<KitOrderItem> KitOrderItems { get; set; }

    public virtual DbSet<LineupPlayer> LineupPlayers { get; set; }

    public virtual DbSet<Match> Matches { get; set; }

    public virtual DbSet<MatchCoach> MatchCoaches { get; set; }

    public virtual DbSet<MatchLineup> MatchLineups { get; set; }

    public virtual DbSet<MatchReport> MatchReports { get; set; }

    public virtual DbSet<MatchSubstitution> MatchSubstitutions { get; set; }

    public virtual DbSet<PerformanceRating> PerformanceRatings { get; set; }

    public virtual DbSet<PersonalSession> PersonalSessions { get; set; }

    public virtual DbSet<PersonalSessionDrill> PersonalSessionDrills { get; set; }

    public virtual DbSet<Player> Players { get; set; }

    public virtual DbSet<PlayerAgeGroup> PlayerAgeGroups { get; set; }

    public virtual DbSet<PlayerAttribute> PlayerAttributes { get; set; }

    public virtual DbSet<PlayerImage> PlayerImages { get; set; }

    public virtual DbSet<PlayerParent> PlayerParents { get; set; }

    public virtual DbSet<PlayerReport> PlayerReports { get; set; }

    public virtual DbSet<PlayerTeam> PlayerTeams { get; set; }

    public virtual DbSet<PositionOverride> PositionOverrides { get; set; }

    public virtual DbSet<ProgressNote> ProgressNotes { get; set; }

    public virtual DbSet<ReportDevelopmentAction> ReportDevelopmentActions { get; set; }

    public virtual DbSet<SessionAttendance> SessionAttendances { get; set; }

    public virtual DbSet<SessionCoach> SessionCoaches { get; set; }

    public virtual DbSet<SessionDrill> SessionDrills { get; set; }

    public virtual DbSet<SimilarProfessional> SimilarProfessionals { get; set; }

    public virtual DbSet<TacticPrinciple> TacticPrinciples { get; set; }

    public virtual DbSet<Team> Teams { get; set; }

    public virtual DbSet<TeamCoach> TeamCoaches { get; set; }

    public virtual DbSet<TemplateDrill> TemplateDrills { get; set; }

    public virtual DbSet<TrainingObjective> TrainingObjectives { get; set; }

    public virtual DbSet<TrainingPlan> TrainingPlans { get; set; }

    public virtual DbSet<TrainingSession> TrainingSessions { get; set; }

    public virtual DbSet<User> Users { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AgeGroup>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__age_grou__3213E83FD256604D");

            entity.ToTable("age_groups");

            entity.HasIndex(e => e.ClubId, "IX_age_groups_club_id");

            entity.HasIndex(e => e.Code, "UQ_age_groups_code").IsUnique();

            entity.Property(e => e.Id)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("id");
            entity.Property(e => e.ClubId).HasColumnName("club_id");
            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("code");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnName("created_at");
            entity.Property(e => e.CurrentSeason)
                .HasMaxLength(20)
                .HasColumnName("current_season");
            entity.Property(e => e.DefaultSeason)
                .HasMaxLength(20)
                .HasColumnName("default_season");
            entity.Property(e => e.DefaultSquadSize)
                .HasMaxLength(20)
                .HasColumnName("default_squad_size");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.IsArchived).HasColumnName("is_archived");
            entity.Property(e => e.Level)
                .HasMaxLength(50)
                .HasColumnName("level");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("name");
            entity.Property(e => e.Seasons).HasColumnName("seasons");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnName("updated_at");

            entity.HasOne(d => d.Club).WithMany(p => p.AgeGroups)
                .HasForeignKey(d => d.ClubId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_age_groups_clubs");
        });

        modelBuilder.Entity<AgeGroupCoordinator>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__age_grou__3213E83F195FCB62");

            entity.ToTable("age_group_coordinators");

            entity.HasIndex(e => e.AgeGroupId, "IX_age_group_coordinators_age_group_id");

            entity.HasIndex(e => e.CoachId, "IX_age_group_coordinators_coach_id");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("id");
            entity.Property(e => e.AgeGroupId).HasColumnName("age_group_id");
            entity.Property(e => e.CoachId).HasColumnName("coach_id");

            entity.HasOne(d => d.AgeGroup).WithMany(p => p.AgeGroupCoordinators)
                .HasForeignKey(d => d.AgeGroupId)
                .HasConstraintName("FK_age_group_coordinators_age_groups");

            entity.HasOne(d => d.Coach).WithMany(p => p.AgeGroupCoordinators)
                .HasForeignKey(d => d.CoachId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_age_group_coordinators_coaches");
        });

        modelBuilder.Entity<AppliedTemplate>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__applied___3213E83F760D96A5");

            entity.ToTable("applied_templates");

            entity.HasIndex(e => e.SessionId, "IX_applied_templates_session_id");

            entity.HasIndex(e => e.TemplateId, "IX_applied_templates_template_id");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("id");
            entity.Property(e => e.AppliedAt)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnName("applied_at");
            entity.Property(e => e.SessionId).HasColumnName("session_id");
            entity.Property(e => e.TemplateId).HasColumnName("template_id");

            entity.HasOne(d => d.Session).WithMany(p => p.AppliedTemplates)
                .HasForeignKey(d => d.SessionId)
                .HasConstraintName("FK_applied_templates_sessions");

            entity.HasOne(d => d.Template).WithMany(p => p.AppliedTemplates)
                .HasForeignKey(d => d.TemplateId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_applied_templates_templates");
        });

        modelBuilder.Entity<AttributeEvaluation>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__attribut__3213E83FD7D2B82D");

            entity.ToTable("attribute_evaluations");

            entity.HasIndex(e => e.EvaluatedBy, "IX_attribute_evaluations_evaluated_by");

            entity.HasIndex(e => e.PlayerId, "IX_attribute_evaluations_player_id");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("id");
            entity.Property(e => e.CoachNotes).HasColumnName("coach_notes");
            entity.Property(e => e.EvaluatedAt)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnName("evaluated_at");
            entity.Property(e => e.EvaluatedBy).HasColumnName("evaluated_by");
            entity.Property(e => e.OverallRating).HasColumnName("overall_rating");
            entity.Property(e => e.PeriodEnd).HasColumnName("period_end");
            entity.Property(e => e.PeriodStart).HasColumnName("period_start");
            entity.Property(e => e.PlayerId).HasColumnName("player_id");

            entity.HasOne(d => d.EvaluatedByNavigation).WithMany(p => p.AttributeEvaluations)
                .HasForeignKey(d => d.EvaluatedBy)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_attribute_evaluations_coaches");

            entity.HasOne(d => d.Player).WithMany(p => p.AttributeEvaluations)
                .HasForeignKey(d => d.PlayerId)
                .HasConstraintName("FK_attribute_evaluations_players");
        });

        modelBuilder.Entity<Card>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__cards__3213E83FC13AF56C");

            entity.ToTable("cards");

            entity.HasIndex(e => e.MatchReportId, "IX_cards_match_report_id");

            entity.HasIndex(e => e.PlayerId, "IX_cards_player_id");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("id");
            entity.Property(e => e.MatchReportId).HasColumnName("match_report_id");
            entity.Property(e => e.Minute).HasColumnName("minute");
            entity.Property(e => e.PlayerId).HasColumnName("player_id");
            entity.Property(e => e.Reason).HasColumnName("reason");
            entity.Property(e => e.Type)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("type");

            entity.HasOne(d => d.MatchReport).WithMany(p => p.Cards)
                .HasForeignKey(d => d.MatchReportId)
                .HasConstraintName("FK_cards_match_reports");

            entity.HasOne(d => d.Player).WithMany(p => p.Cards)
                .HasForeignKey(d => d.PlayerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_cards_players");
        });

        modelBuilder.Entity<Club>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__clubs__3213E83F90D99854");

            entity.ToTable("clubs");

            entity.HasIndex(e => e.Name, "IX_clubs_name");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("id");
            entity.Property(e => e.AccentColor)
                .HasMaxLength(7)
                .HasColumnName("accent_color");
            entity.Property(e => e.Address).HasColumnName("address");
            entity.Property(e => e.City)
                .HasMaxLength(100)
                .HasColumnName("city");
            entity.Property(e => e.Country)
                .HasMaxLength(100)
                .HasColumnName("country");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnName("created_at");
            entity.Property(e => e.Ethos).HasColumnName("ethos");
            entity.Property(e => e.FoundedYear).HasColumnName("founded_year");
            entity.Property(e => e.History).HasColumnName("history");
            entity.Property(e => e.Logo).HasColumnName("logo");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("name");
            entity.Property(e => e.PrimaryColor)
                .HasMaxLength(7)
                .HasColumnName("primary_color");
            entity.Property(e => e.Principles).HasColumnName("principles");
            entity.Property(e => e.SecondaryColor)
                .HasMaxLength(7)
                .HasColumnName("secondary_color");
            entity.Property(e => e.ShortName)
                .HasMaxLength(50)
                .HasColumnName("short_name");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnName("updated_at");
            entity.Property(e => e.Venue)
                .HasMaxLength(255)
                .HasColumnName("venue");
        });

        modelBuilder.Entity<Coach>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__coaches__3213E83FF7621232");

            entity.ToTable("coaches");

            entity.HasIndex(e => e.ClubId, "IX_coaches_club_id");

            entity.HasIndex(e => e.Email, "IX_coaches_email");

            entity.HasIndex(e => e.Email, "UQ__coaches__AB6E6164A08CD3B5").IsUnique();

            entity.Property(e => e.Id)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("id");
            entity.Property(e => e.AssociationId)
                .HasMaxLength(50)
                .HasColumnName("association_id");
            entity.Property(e => e.Biography).HasColumnName("biography");
            entity.Property(e => e.ClubId).HasColumnName("club_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnName("created_at");
            entity.Property(e => e.DateOfBirth).HasColumnName("date_of_birth");
            entity.Property(e => e.Email)
                .HasMaxLength(255)
                .HasColumnName("email");
            entity.Property(e => e.FirstName)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("first_name");
            entity.Property(e => e.HasAccount).HasColumnName("has_account");
            entity.Property(e => e.IsArchived).HasColumnName("is_archived");
            entity.Property(e => e.LastName)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("last_name");
            entity.Property(e => e.Phone)
                .HasMaxLength(50)
                .HasColumnName("phone");
            entity.Property(e => e.Photo).HasColumnName("photo");
            entity.Property(e => e.Role)
                .HasMaxLength(50)
                .HasColumnName("role");
            entity.Property(e => e.Specializations).HasColumnName("specializations");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnName("updated_at");

            entity.HasOne(d => d.Club).WithMany(p => p.Coaches)
                .HasForeignKey(d => d.ClubId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_coaches_clubs");
        });

        modelBuilder.Entity<DevelopmentGoal>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__developm__3213E83FBC7F50B5");

            entity.ToTable("development_goals");

            entity.HasIndex(e => e.PlanId, "IX_development_goals_plan_id");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("id");
            entity.Property(e => e.Actions).HasColumnName("actions");
            entity.Property(e => e.Completed).HasColumnName("completed");
            entity.Property(e => e.CompletedDate).HasColumnName("completed_date");
            entity.Property(e => e.Goal)
                .IsRequired()
                .HasColumnName("goal");
            entity.Property(e => e.PlanId).HasColumnName("plan_id");
            entity.Property(e => e.Progress).HasColumnName("progress");
            entity.Property(e => e.StartDate).HasColumnName("start_date");
            entity.Property(e => e.TargetDate).HasColumnName("target_date");

            entity.HasOne(d => d.Plan).WithMany(p => p.DevelopmentGoals)
                .HasForeignKey(d => d.PlanId)
                .HasConstraintName("FK_development_goals_plans");
        });

        modelBuilder.Entity<DevelopmentPlan>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__developm__3213E83FA9FF0F7C");

            entity.ToTable("development_plans");

            entity.HasIndex(e => e.CreatedBy, "IX_development_plans_created_by");

            entity.HasIndex(e => e.PlayerId, "IX_development_plans_player_id");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("id");
            entity.Property(e => e.CoachNotes).HasColumnName("coach_notes");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnName("created_at");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.LinkedReportId).HasColumnName("linked_report_id");
            entity.Property(e => e.PeriodEnd).HasColumnName("period_end");
            entity.Property(e => e.PeriodStart).HasColumnName("period_start");
            entity.Property(e => e.PlayerId).HasColumnName("player_id");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("status");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("title");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnName("updated_at");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.DevelopmentPlans)
                .HasForeignKey(d => d.CreatedBy)
                .HasConstraintName("FK_development_plans_coaches");

            entity.HasOne(d => d.LinkedReport).WithMany(p => p.DevelopmentPlans)
                .HasForeignKey(d => d.LinkedReportId)
                .HasConstraintName("FK_development_plans_reports");

            entity.HasOne(d => d.Player).WithMany(p => p.DevelopmentPlans)
                .HasForeignKey(d => d.PlayerId)
                .HasConstraintName("FK_development_plans_players");
        });

        modelBuilder.Entity<Drill>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__drills__3213E83F7AF2D710");

            entity.ToTable("drills");

            entity.HasIndex(e => e.ClubId, "IX_drills_club_id");

            entity.HasIndex(e => e.CreatedBy, "IX_drills_created_by");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("id");
            entity.Property(e => e.Attributes).HasColumnName("attributes");
            entity.Property(e => e.Category)
                .HasMaxLength(50)
                .HasColumnName("category");
            entity.Property(e => e.ClubId).HasColumnName("club_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnName("created_at");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.Diagram).HasColumnName("diagram");
            entity.Property(e => e.DurationMinutes).HasColumnName("duration_minutes");
            entity.Property(e => e.Equipment).HasColumnName("equipment");
            entity.Property(e => e.Instructions).HasColumnName("instructions");
            entity.Property(e => e.IsPublic).HasColumnName("is_public");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("name");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnName("updated_at");
            entity.Property(e => e.Variations).HasColumnName("variations");

            entity.HasOne(d => d.Club).WithMany(p => p.Drills)
                .HasForeignKey(d => d.ClubId)
                .HasConstraintName("FK_drills_clubs");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.Drills)
                .HasForeignKey(d => d.CreatedBy)
                .HasConstraintName("FK_drills_coaches");
        });

        modelBuilder.Entity<DrillLink>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__drill_li__3213E83F037FF3DD");

            entity.ToTable("drill_links");

            entity.HasIndex(e => e.DrillId, "IX_drill_links_drill_id");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("id");
            entity.Property(e => e.DrillId).HasColumnName("drill_id");
            entity.Property(e => e.Title)
                .HasMaxLength(255)
                .HasColumnName("title");
            entity.Property(e => e.Type)
                .HasMaxLength(50)
                .HasColumnName("type");
            entity.Property(e => e.Url)
                .IsRequired()
                .HasColumnName("url");

            entity.HasOne(d => d.Drill).WithMany(p => p.DrillLinks)
                .HasForeignKey(d => d.DrillId)
                .HasConstraintName("FK_drill_links_drills");
        });

        modelBuilder.Entity<DrillTemplate>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__drill_te__3213E83F9A2BD378");

            entity.ToTable("drill_templates");

            entity.HasIndex(e => e.ClubId, "IX_drill_templates_club_id");

            entity.HasIndex(e => e.CreatedBy, "IX_drill_templates_created_by");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("id");
            entity.Property(e => e.AggregatedAttributes).HasColumnName("aggregated_attributes");
            entity.Property(e => e.Category)
                .HasMaxLength(50)
                .HasColumnName("category");
            entity.Property(e => e.ClubId).HasColumnName("club_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnName("created_at");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.IsPublic).HasColumnName("is_public");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("name");
            entity.Property(e => e.TotalDuration).HasColumnName("total_duration");

            entity.HasOne(d => d.Club).WithMany(p => p.DrillTemplates)
                .HasForeignKey(d => d.ClubId)
                .HasConstraintName("FK_drill_templates_clubs");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.DrillTemplates)
                .HasForeignKey(d => d.CreatedBy)
                .HasConstraintName("FK_drill_templates_coaches");
        });

        modelBuilder.Entity<EmergencyContact>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__emergenc__3213E83F118B54B9");

            entity.ToTable("emergency_contacts");

            entity.HasIndex(e => e.PlayerId, "IX_emergency_contacts_player_id");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("id");
            entity.Property(e => e.IsPrimary).HasColumnName("is_primary");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("name");
            entity.Property(e => e.Phone)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("phone");
            entity.Property(e => e.PlayerId).HasColumnName("player_id");
            entity.Property(e => e.Relationship)
                .HasMaxLength(100)
                .HasColumnName("relationship");

            entity.HasOne(d => d.Player).WithMany(p => p.EmergencyContacts)
                .HasForeignKey(d => d.PlayerId)
                .HasConstraintName("FK_emergency_contacts_players");
        });

        modelBuilder.Entity<EvaluationAttribute>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__evaluati__3213E83FE02D795A");

            entity.ToTable("evaluation_attributes");

            entity.HasIndex(e => e.EvaluationId, "IX_evaluation_attributes_evaluation_id");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("id");
            entity.Property(e => e.AttributeName)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("attribute_name");
            entity.Property(e => e.EvaluationId).HasColumnName("evaluation_id");
            entity.Property(e => e.Notes).HasColumnName("notes");
            entity.Property(e => e.Rating).HasColumnName("rating");

            entity.HasOne(d => d.Evaluation).WithMany(p => p.EvaluationAttributes)
                .HasForeignKey(d => d.EvaluationId)
                .HasConstraintName("FK_evaluation_attributes_attribute_evaluations");
        });

        modelBuilder.Entity<Formation>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__formatio__3213E83F38DDFD7B");

            entity.ToTable("formations");

            entity.HasIndex(e => e.CreatedBy, "IX_formations_created_by");

            entity.HasIndex(e => e.ParentFormationId, "IX_formations_parent_formation_id");

            entity.HasIndex(e => e.ParentTacticId, "IX_formations_parent_tactic_id");

            entity.HasIndex(e => e.ScopeClubId, "IX_formations_scope_club_id");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnName("created_at");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.IsSystemFormation).HasColumnName("is_system_formation");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("name");
            entity.Property(e => e.ParentFormationId).HasColumnName("parent_formation_id");
            entity.Property(e => e.ParentTacticId).HasColumnName("parent_tactic_id");
            entity.Property(e => e.ScopeAgeGroupId).HasColumnName("scope_age_group_id");
            entity.Property(e => e.ScopeClubId).HasColumnName("scope_club_id");
            entity.Property(e => e.ScopeTeamId).HasColumnName("scope_team_id");
            entity.Property(e => e.ScopeType)
                .HasMaxLength(50)
                .HasColumnName("scope_type");
            entity.Property(e => e.SquadSize)
                .HasMaxLength(20)
                .HasColumnName("squad_size");
            entity.Property(e => e.Style)
                .HasMaxLength(50)
                .HasColumnName("style");
            entity.Property(e => e.Summary).HasColumnName("summary");
            entity.Property(e => e.System)
                .HasMaxLength(20)
                .HasColumnName("system");
            entity.Property(e => e.Tags).HasColumnName("tags");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnName("updated_at");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.Formations)
                .HasForeignKey(d => d.CreatedBy)
                .HasConstraintName("FK_formations_created_by");

            entity.HasOne(d => d.ParentFormation).WithMany(p => p.InverseParentFormation)
                .HasForeignKey(d => d.ParentFormationId)
                .HasConstraintName("FK_formations_parent_formation");

            entity.HasOne(d => d.ParentTactic).WithMany(p => p.InverseParentTactic)
                .HasForeignKey(d => d.ParentTacticId)
                .HasConstraintName("FK_formations_parent_tactic");

            entity.HasOne(d => d.ScopeClub).WithMany(p => p.Formations)
                .HasForeignKey(d => d.ScopeClubId)
                .HasConstraintName("FK_formations_scope_club");
        });

        modelBuilder.Entity<FormationPosition>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__formatio__3213E83FB6860F5C");

            entity.ToTable("formation_positions");

            entity.HasIndex(e => e.FormationId, "IX_formation_positions_formation_id");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("id");
            entity.Property(e => e.Direction)
                .HasMaxLength(20)
                .HasColumnName("direction");
            entity.Property(e => e.FormationId).HasColumnName("formation_id");
            entity.Property(e => e.Position)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("position");
            entity.Property(e => e.PositionIndex).HasColumnName("position_index");
            entity.Property(e => e.XCoord)
                .HasColumnType("decimal(5, 2)")
                .HasColumnName("x_coord");
            entity.Property(e => e.YCoord)
                .HasColumnType("decimal(5, 2)")
                .HasColumnName("y_coord");

            entity.HasOne(d => d.Formation).WithMany(p => p.FormationPositions)
                .HasForeignKey(d => d.FormationId)
                .HasConstraintName("FK_formation_positions_formations");
        });

        modelBuilder.Entity<Goal>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__goals__3213E83F0ABABB23");

            entity.ToTable("goals");

            entity.HasIndex(e => e.MatchReportId, "IX_goals_match_report_id");

            entity.HasIndex(e => e.PlayerId, "IX_goals_player_id");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("id");
            entity.Property(e => e.AssistPlayerId).HasColumnName("assist_player_id");
            entity.Property(e => e.MatchReportId).HasColumnName("match_report_id");
            entity.Property(e => e.Minute).HasColumnName("minute");
            entity.Property(e => e.PlayerId).HasColumnName("player_id");

            entity.HasOne(d => d.AssistPlayer).WithMany(p => p.GoalAssistPlayers)
                .HasForeignKey(d => d.AssistPlayerId)
                .HasConstraintName("FK_goals_assist_player");

            entity.HasOne(d => d.MatchReport).WithMany(p => p.Goals)
                .HasForeignKey(d => d.MatchReportId)
                .HasConstraintName("FK_goals_match_reports");

            entity.HasOne(d => d.Player).WithMany(p => p.GoalPlayers)
                .HasForeignKey(d => d.PlayerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_goals_player");
        });

        modelBuilder.Entity<Injury>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__injuries__3213E83F1CC821F1");

            entity.ToTable("injuries");

            entity.HasIndex(e => e.MatchReportId, "IX_injuries_match_report_id");

            entity.HasIndex(e => e.PlayerId, "IX_injuries_player_id");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("id");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.MatchReportId).HasColumnName("match_report_id");
            entity.Property(e => e.Minute).HasColumnName("minute");
            entity.Property(e => e.PlayerId).HasColumnName("player_id");
            entity.Property(e => e.Severity)
                .HasMaxLength(50)
                .HasColumnName("severity");

            entity.HasOne(d => d.MatchReport).WithMany(p => p.Injuries)
                .HasForeignKey(d => d.MatchReportId)
                .HasConstraintName("FK_injuries_match_reports");

            entity.HasOne(d => d.Player).WithMany(p => p.Injuries)
                .HasForeignKey(d => d.PlayerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_injuries_players");
        });

        modelBuilder.Entity<Kit>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__kits__3213E83FC0FE0600");

            entity.ToTable("kits");

            entity.HasIndex(e => e.ClubId, "IX_kits_club_id");

            entity.HasIndex(e => e.TeamId, "IX_kits_team_id");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("id");
            entity.Property(e => e.ClubId).HasColumnName("club_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnName("created_at");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("is_active");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("name");
            entity.Property(e => e.Season)
                .HasMaxLength(20)
                .HasColumnName("season");
            entity.Property(e => e.ShirtColor)
                .HasMaxLength(7)
                .HasColumnName("shirt_color");
            entity.Property(e => e.ShortsColor)
                .HasMaxLength(7)
                .HasColumnName("shorts_color");
            entity.Property(e => e.SocksColor)
                .HasMaxLength(7)
                .HasColumnName("socks_color");
            entity.Property(e => e.TeamId).HasColumnName("team_id");
            entity.Property(e => e.Type)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("type");

            entity.HasOne(d => d.Club).WithMany(p => p.Kits)
                .HasForeignKey(d => d.ClubId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_kits_clubs");

            entity.HasOne(d => d.Team).WithMany(p => p.Kits)
                .HasForeignKey(d => d.TeamId)
                .HasConstraintName("FK_kits_teams");
        });

        modelBuilder.Entity<KitOrder>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__kit_orde__3213E83FCB8E66C9");

            entity.ToTable("kit_orders");

            entity.HasIndex(e => e.OrderedBy, "IX_kit_orders_ordered_by");

            entity.HasIndex(e => e.PlayerId, "IX_kit_orders_player_id");

            entity.HasIndex(e => e.TeamId, "IX_kit_orders_team_id");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("id");
            entity.Property(e => e.OrderedAt)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnName("ordered_at");
            entity.Property(e => e.OrderedBy).HasColumnName("ordered_by");
            entity.Property(e => e.PlayerId).HasColumnName("player_id");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("status");
            entity.Property(e => e.TeamId).HasColumnName("team_id");
            entity.Property(e => e.TotalAmount)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("total_amount");

            entity.HasOne(d => d.OrderedByNavigation).WithMany(p => p.KitOrders)
                .HasForeignKey(d => d.OrderedBy)
                .HasConstraintName("FK_kit_orders_users");

            entity.HasOne(d => d.Player).WithMany(p => p.KitOrders)
                .HasForeignKey(d => d.PlayerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_kit_orders_players");

            entity.HasOne(d => d.Team).WithMany(p => p.KitOrders)
                .HasForeignKey(d => d.TeamId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_kit_orders_teams");
        });

        modelBuilder.Entity<KitOrderItem>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__kit_orde__3213E83FC2634F4E");

            entity.ToTable("kit_order_items");

            entity.HasIndex(e => e.OrderId, "IX_kit_order_items_order_id");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("id");
            entity.Property(e => e.OrderId).HasColumnName("order_id");
            entity.Property(e => e.Price)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("price");
            entity.Property(e => e.Quantity).HasColumnName("quantity");
            entity.Property(e => e.Size)
                .HasMaxLength(20)
                .HasColumnName("size");
            entity.Property(e => e.Type)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("type");

            entity.HasOne(d => d.Order).WithMany(p => p.KitOrderItems)
                .HasForeignKey(d => d.OrderId)
                .HasConstraintName("FK_kit_order_items_orders");
        });

        modelBuilder.Entity<LineupPlayer>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__lineup_p__3213E83F5483EF81");

            entity.ToTable("lineup_players");

            entity.HasIndex(e => e.LineupId, "IX_lineup_players_lineup_id");

            entity.HasIndex(e => e.PlayerId, "IX_lineup_players_player_id");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("id");
            entity.Property(e => e.IsStarting)
                .HasDefaultValue(true)
                .HasColumnName("is_starting");
            entity.Property(e => e.LineupId).HasColumnName("lineup_id");
            entity.Property(e => e.PlayerId).HasColumnName("player_id");
            entity.Property(e => e.Position)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("position");
            entity.Property(e => e.SquadNumber).HasColumnName("squad_number");

            entity.HasOne(d => d.Lineup).WithMany(p => p.LineupPlayers)
                .HasForeignKey(d => d.LineupId)
                .HasConstraintName("FK_lineup_players_lineups");

            entity.HasOne(d => d.Player).WithMany(p => p.LineupPlayers)
                .HasForeignKey(d => d.PlayerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_lineup_players_players");
        });

        modelBuilder.Entity<Match>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__matches__3213E83F8BFA3B4C");

            entity.ToTable("matches");

            entity.HasIndex(e => e.MatchDate, "IX_matches_match_date");

            entity.HasIndex(e => e.TeamId, "IX_matches_team_id");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("id");
            entity.Property(e => e.AwayScore).HasColumnName("away_score");
            entity.Property(e => e.Competition)
                .HasMaxLength(100)
                .HasColumnName("competition");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnName("created_at");
            entity.Property(e => e.GoalkeeperKitId).HasColumnName("goalkeeper_kit_id");
            entity.Property(e => e.HomeScore).HasColumnName("home_score");
            entity.Property(e => e.IsHome)
                .HasDefaultValue(true)
                .HasColumnName("is_home");
            entity.Property(e => e.IsLocked).HasColumnName("is_locked");
            entity.Property(e => e.KickOffTime).HasColumnName("kick_off_time");
            entity.Property(e => e.Location)
                .HasMaxLength(255)
                .HasColumnName("location");
            entity.Property(e => e.MatchDate).HasColumnName("match_date");
            entity.Property(e => e.MeetTime).HasColumnName("meet_time");
            entity.Property(e => e.Notes).HasColumnName("notes");
            entity.Property(e => e.Opposition)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("opposition");
            entity.Property(e => e.PrimaryKitId).HasColumnName("primary_kit_id");
            entity.Property(e => e.SeasonId)
                .HasMaxLength(20)
                .HasColumnName("season_id");
            entity.Property(e => e.SecondaryKitId).HasColumnName("secondary_kit_id");
            entity.Property(e => e.SquadSize)
                .HasMaxLength(20)
                .HasColumnName("squad_size");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("status");
            entity.Property(e => e.TeamId).HasColumnName("team_id");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnName("updated_at");
            entity.Property(e => e.WeatherCondition)
                .HasMaxLength(50)
                .HasColumnName("weather_condition");
            entity.Property(e => e.WeatherTemperature).HasColumnName("weather_temperature");

            entity.HasOne(d => d.GoalkeeperKit).WithMany(p => p.MatchGoalkeeperKits)
                .HasForeignKey(d => d.GoalkeeperKitId)
                .HasConstraintName("FK_matches_goalkeeper_kit");

            entity.HasOne(d => d.PrimaryKit).WithMany(p => p.MatchPrimaryKits)
                .HasForeignKey(d => d.PrimaryKitId)
                .HasConstraintName("FK_matches_primary_kit");

            entity.HasOne(d => d.SecondaryKit).WithMany(p => p.MatchSecondaryKits)
                .HasForeignKey(d => d.SecondaryKitId)
                .HasConstraintName("FK_matches_secondary_kit");

            entity.HasOne(d => d.Team).WithMany(p => p.Matches)
                .HasForeignKey(d => d.TeamId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_matches_teams");
        });

        modelBuilder.Entity<MatchCoach>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__match_co__3213E83FFBA39367");

            entity.ToTable("match_coaches");

            entity.HasIndex(e => e.CoachId, "IX_match_coaches_coach_id");

            entity.HasIndex(e => e.MatchId, "IX_match_coaches_match_id");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("id");
            entity.Property(e => e.CoachId).HasColumnName("coach_id");
            entity.Property(e => e.MatchId).HasColumnName("match_id");

            entity.HasOne(d => d.Coach).WithMany(p => p.MatchCoaches)
                .HasForeignKey(d => d.CoachId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_match_coaches_coaches");

            entity.HasOne(d => d.Match).WithMany(p => p.MatchCoaches)
                .HasForeignKey(d => d.MatchId)
                .HasConstraintName("FK_match_coaches_matches");
        });

        modelBuilder.Entity<MatchLineup>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__match_li__3213E83F71876730");

            entity.ToTable("match_lineups");

            entity.HasIndex(e => e.MatchId, "IX_match_lineups_match_id");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("id");
            entity.Property(e => e.FormationId).HasColumnName("formation_id");
            entity.Property(e => e.MatchId).HasColumnName("match_id");
            entity.Property(e => e.TacticId).HasColumnName("tactic_id");

            entity.HasOne(d => d.Formation).WithMany(p => p.MatchLineupFormations)
                .HasForeignKey(d => d.FormationId)
                .HasConstraintName("FK_match_lineups_formation");

            entity.HasOne(d => d.Match).WithMany(p => p.MatchLineups)
                .HasForeignKey(d => d.MatchId)
                .HasConstraintName("FK_match_lineups_matches");

            entity.HasOne(d => d.Tactic).WithMany(p => p.MatchLineupTactics)
                .HasForeignKey(d => d.TacticId)
                .HasConstraintName("FK_match_lineups_tactic");
        });

        modelBuilder.Entity<MatchReport>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__match_re__3213E83F70F4AC39");

            entity.ToTable("match_reports");

            entity.HasIndex(e => e.MatchId, "IX_match_reports_match_id");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("id");
            entity.Property(e => e.CaptainId).HasColumnName("captain_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnName("created_at");
            entity.Property(e => e.MatchId).HasColumnName("match_id");
            entity.Property(e => e.PlayerOfMatchId).HasColumnName("player_of_match_id");
            entity.Property(e => e.Summary).HasColumnName("summary");

            entity.HasOne(d => d.Captain).WithMany(p => p.MatchReportCaptains)
                .HasForeignKey(d => d.CaptainId)
                .HasConstraintName("FK_match_reports_captain");

            entity.HasOne(d => d.Match).WithMany(p => p.MatchReports)
                .HasForeignKey(d => d.MatchId)
                .HasConstraintName("FK_match_reports_matches");

            entity.HasOne(d => d.PlayerOfMatch).WithMany(p => p.MatchReportPlayerOfMatches)
                .HasForeignKey(d => d.PlayerOfMatchId)
                .HasConstraintName("FK_match_reports_player_of_match");
        });

        modelBuilder.Entity<MatchSubstitution>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__match_su__3213E83FBFAD767A");

            entity.ToTable("match_substitutions");

            entity.HasIndex(e => e.MatchId, "IX_match_substitutions_match_id");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("id");
            entity.Property(e => e.MatchId).HasColumnName("match_id");
            entity.Property(e => e.Minute).HasColumnName("minute");
            entity.Property(e => e.PlayerInId).HasColumnName("player_in_id");
            entity.Property(e => e.PlayerOutId).HasColumnName("player_out_id");

            entity.HasOne(d => d.Match).WithMany(p => p.MatchSubstitutions)
                .HasForeignKey(d => d.MatchId)
                .HasConstraintName("FK_match_substitutions_matches");

            entity.HasOne(d => d.PlayerIn).WithMany(p => p.MatchSubstitutionPlayerIns)
                .HasForeignKey(d => d.PlayerInId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_match_substitutions_player_in");

            entity.HasOne(d => d.PlayerOut).WithMany(p => p.MatchSubstitutionPlayerOuts)
                .HasForeignKey(d => d.PlayerOutId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_match_substitutions_player_out");
        });

        modelBuilder.Entity<PerformanceRating>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__performa__3213E83F4F6C0CA5");

            entity.ToTable("performance_ratings");

            entity.HasIndex(e => e.MatchReportId, "IX_performance_ratings_match_report_id");

            entity.HasIndex(e => e.PlayerId, "IX_performance_ratings_player_id");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("id");
            entity.Property(e => e.MatchReportId).HasColumnName("match_report_id");
            entity.Property(e => e.PlayerId).HasColumnName("player_id");
            entity.Property(e => e.Rating)
                .HasColumnType("decimal(3, 1)")
                .HasColumnName("rating");

            entity.HasOne(d => d.MatchReport).WithMany(p => p.PerformanceRatings)
                .HasForeignKey(d => d.MatchReportId)
                .HasConstraintName("FK_performance_ratings_match_reports");

            entity.HasOne(d => d.Player).WithMany(p => p.PerformanceRatings)
                .HasForeignKey(d => d.PlayerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_performance_ratings_players");
        });

        modelBuilder.Entity<PersonalSession>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__personal__3213E83F28FCC8CB");

            entity.ToTable("personal_sessions");

            entity.HasIndex(e => e.PlanId, "IX_personal_sessions_plan_id");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("id");
            entity.Property(e => e.Completed).HasColumnName("completed");
            entity.Property(e => e.FocusAreas).HasColumnName("focus_areas");
            entity.Property(e => e.Notes).HasColumnName("notes");
            entity.Property(e => e.PlanId).HasColumnName("plan_id");
            entity.Property(e => e.SessionDate).HasColumnName("session_date");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("title");

            entity.HasOne(d => d.Plan).WithMany(p => p.PersonalSessions)
                .HasForeignKey(d => d.PlanId)
                .HasConstraintName("FK_personal_sessions_plans");
        });

        modelBuilder.Entity<PersonalSessionDrill>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__personal__3213E83F015C6CC1");

            entity.ToTable("personal_session_drills");

            entity.HasIndex(e => e.DrillId, "IX_personal_session_drills_drill_id");

            entity.HasIndex(e => e.PersonalSessionId, "IX_personal_session_drills_personal_session_id");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("id");
            entity.Property(e => e.DrillId).HasColumnName("drill_id");
            entity.Property(e => e.PersonalSessionId).HasColumnName("personal_session_id");

            entity.HasOne(d => d.Drill).WithMany(p => p.PersonalSessionDrills)
                .HasForeignKey(d => d.DrillId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_personal_session_drills_drills");

            entity.HasOne(d => d.PersonalSession).WithMany(p => p.PersonalSessionDrills)
                .HasForeignKey(d => d.PersonalSessionId)
                .HasConstraintName("FK_personal_session_drills_sessions");
        });

        modelBuilder.Entity<Player>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__players__3213E83F7475920E");

            entity.ToTable("players");

            entity.HasIndex(e => e.ClubId, "IX_players_club_id");

            entity.HasIndex(e => e.DateOfBirth, "IX_players_date_of_birth");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("id");
            entity.Property(e => e.Allergies).HasColumnName("allergies");
            entity.Property(e => e.AssociationId)
                .HasMaxLength(50)
                .HasColumnName("association_id");
            entity.Property(e => e.ClubId).HasColumnName("club_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnName("created_at");
            entity.Property(e => e.DateOfBirth).HasColumnName("date_of_birth");
            entity.Property(e => e.FirstName)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("first_name");
            entity.Property(e => e.IsArchived).HasColumnName("is_archived");
            entity.Property(e => e.LastName)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("last_name");
            entity.Property(e => e.MedicalConditions).HasColumnName("medical_conditions");
            entity.Property(e => e.Nickname)
                .HasMaxLength(50)
                .HasColumnName("nickname");
            entity.Property(e => e.OverallRating).HasColumnName("overall_rating");
            entity.Property(e => e.Photo).HasColumnName("photo");
            entity.Property(e => e.PreferredPositions).HasColumnName("preferred_positions");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnName("updated_at");

            entity.HasOne(d => d.Club).WithMany(p => p.Players)
                .HasForeignKey(d => d.ClubId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_players_clubs");
        });

        modelBuilder.Entity<PlayerAgeGroup>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__player_a__3213E83FB74CAE96");

            entity.ToTable("player_age_groups");

            entity.HasIndex(e => e.AgeGroupId, "IX_player_age_groups_age_group_id");

            entity.HasIndex(e => e.PlayerId, "IX_player_age_groups_player_id");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("id");
            entity.Property(e => e.AgeGroupId).HasColumnName("age_group_id");
            entity.Property(e => e.PlayerId).HasColumnName("player_id");

            entity.HasOne(d => d.AgeGroup).WithMany(p => p.PlayerAgeGroups)
                .HasForeignKey(d => d.AgeGroupId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_player_age_groups_age_groups");

            entity.HasOne(d => d.Player).WithMany(p => p.PlayerAgeGroups)
                .HasForeignKey(d => d.PlayerId)
                .HasConstraintName("FK_player_age_groups_players");
        });

        modelBuilder.Entity<PlayerAttribute>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__player_a__3213E83F8CF092CC");

            entity.ToTable("player_attributes");

            entity.HasIndex(e => e.PlayerId, "IX_player_attributes_player_id");

            entity.HasIndex(e => e.PlayerId, "UQ__player_a__44DA120DA93BCE45").IsUnique();

            entity.Property(e => e.Id)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("id");
            entity.Property(e => e.Acceleration).HasColumnName("acceleration");
            entity.Property(e => e.Aggression).HasColumnName("aggression");
            entity.Property(e => e.Agility).HasColumnName("agility");
            entity.Property(e => e.AttackingPosition).HasColumnName("attacking_position");
            entity.Property(e => e.Awareness).HasColumnName("awareness");
            entity.Property(e => e.Balance).HasColumnName("balance");
            entity.Property(e => e.BallControl).HasColumnName("ball_control");
            entity.Property(e => e.Communication).HasColumnName("communication");
            entity.Property(e => e.Composure).HasColumnName("composure");
            entity.Property(e => e.Crossing).HasColumnName("crossing");
            entity.Property(e => e.DefensivePositioning).HasColumnName("defensive_positioning");
            entity.Property(e => e.Dribbling).HasColumnName("dribbling");
            entity.Property(e => e.Finishing).HasColumnName("finishing");
            entity.Property(e => e.FreeKick).HasColumnName("free_kick");
            entity.Property(e => e.Heading).HasColumnName("heading");
            entity.Property(e => e.Interceptions).HasColumnName("interceptions");
            entity.Property(e => e.Jumping).HasColumnName("jumping");
            entity.Property(e => e.LongPassing).HasColumnName("long_passing");
            entity.Property(e => e.LongShot).HasColumnName("long_shot");
            entity.Property(e => e.Marking).HasColumnName("marking");
            entity.Property(e => e.Pace).HasColumnName("pace");
            entity.Property(e => e.Penalties).HasColumnName("penalties");
            entity.Property(e => e.PlayerId).HasColumnName("player_id");
            entity.Property(e => e.Positioning).HasColumnName("positioning");
            entity.Property(e => e.Positivity).HasColumnName("positivity");
            entity.Property(e => e.Reactions).HasColumnName("reactions");
            entity.Property(e => e.ShortPassing).HasColumnName("short_passing");
            entity.Property(e => e.ShotPower).HasColumnName("shot_power");
            entity.Property(e => e.SlidingTackle).HasColumnName("sliding_tackle");
            entity.Property(e => e.SprintSpeed).HasColumnName("sprint_speed");
            entity.Property(e => e.Stamina).HasColumnName("stamina");
            entity.Property(e => e.StandingTackle).HasColumnName("standing_tackle");
            entity.Property(e => e.Strength).HasColumnName("strength");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnName("updated_at");
            entity.Property(e => e.Vision).HasColumnName("vision");
            entity.Property(e => e.Volleys).HasColumnName("volleys");
            entity.Property(e => e.WeakFoot).HasColumnName("weak_foot");

            entity.HasOne(d => d.Player).WithOne(p => p.PlayerAttribute)
                .HasForeignKey<PlayerAttribute>(d => d.PlayerId)
                .HasConstraintName("FK_player_attributes_players");
        });

        modelBuilder.Entity<PlayerImage>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__player_i__3213E83F8B4B802D");

            entity.ToTable("player_images");

            entity.HasIndex(e => e.PlayerId, "IX_player_images_player_id");

            entity.HasIndex(e => e.UploadedBy, "IX_player_images_uploaded_by");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("id");
            entity.Property(e => e.Caption)
                .HasMaxLength(255)
                .HasColumnName("caption");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnName("created_at");
            entity.Property(e => e.PhotoDate).HasColumnName("photo_date");
            entity.Property(e => e.PlayerId).HasColumnName("player_id");
            entity.Property(e => e.Tags).HasColumnName("tags");
            entity.Property(e => e.UploadedBy).HasColumnName("uploaded_by");
            entity.Property(e => e.Url)
                .IsRequired()
                .HasColumnName("url");

            entity.HasOne(d => d.Player).WithMany(p => p.PlayerImages)
                .HasForeignKey(d => d.PlayerId)
                .HasConstraintName("FK_player_images_players");

            entity.HasOne(d => d.UploadedByNavigation).WithMany(p => p.PlayerImages)
                .HasForeignKey(d => d.UploadedBy)
                .HasConstraintName("FK_player_images_users");
        });

        modelBuilder.Entity<PlayerParent>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__player_p__3213E83F7FF2FA24");

            entity.ToTable("player_parents");

            entity.HasIndex(e => e.ParentUserId, "IX_player_parents_parent_user_id");

            entity.HasIndex(e => e.PlayerId, "IX_player_parents_player_id");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("id");
            entity.Property(e => e.ParentUserId).HasColumnName("parent_user_id");
            entity.Property(e => e.PlayerId).HasColumnName("player_id");

            entity.HasOne(d => d.ParentUser).WithMany(p => p.PlayerParents)
                .HasForeignKey(d => d.ParentUserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_player_parents_users");

            entity.HasOne(d => d.Player).WithMany(p => p.PlayerParents)
                .HasForeignKey(d => d.PlayerId)
                .HasConstraintName("FK_player_parents_players");
        });

        modelBuilder.Entity<PlayerReport>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__player_r__3213E83FF9BBA024");

            entity.ToTable("player_reports");

            entity.HasIndex(e => e.CreatedBy, "IX_player_reports_created_by");

            entity.HasIndex(e => e.PlayerId, "IX_player_reports_player_id");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("id");
            entity.Property(e => e.AreasForImprovement).HasColumnName("areas_for_improvement");
            entity.Property(e => e.CoachComments).HasColumnName("coach_comments");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnName("created_at");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.OverallRating)
                .HasColumnType("decimal(3, 1)")
                .HasColumnName("overall_rating");
            entity.Property(e => e.PeriodEnd).HasColumnName("period_end");
            entity.Property(e => e.PeriodStart).HasColumnName("period_start");
            entity.Property(e => e.PlayerId).HasColumnName("player_id");
            entity.Property(e => e.Strengths).HasColumnName("strengths");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.PlayerReports)
                .HasForeignKey(d => d.CreatedBy)
                .HasConstraintName("FK_player_reports_coaches");

            entity.HasOne(d => d.Player).WithMany(p => p.PlayerReports)
                .HasForeignKey(d => d.PlayerId)
                .HasConstraintName("FK_player_reports_players");
        });

        modelBuilder.Entity<PlayerTeam>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__player_t__3213E83FDFD59070");

            entity.ToTable("player_teams");

            entity.HasIndex(e => e.PlayerId, "IX_player_teams_player_id");

            entity.HasIndex(e => e.TeamId, "IX_player_teams_team_id");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("id");
            entity.Property(e => e.AssignedAt)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnName("assigned_at");
            entity.Property(e => e.PlayerId).HasColumnName("player_id");
            entity.Property(e => e.SquadNumber).HasColumnName("squad_number");
            entity.Property(e => e.TeamId).HasColumnName("team_id");

            entity.HasOne(d => d.Player).WithMany(p => p.PlayerTeams)
                .HasForeignKey(d => d.PlayerId)
                .HasConstraintName("FK_player_teams_players");

            entity.HasOne(d => d.Team).WithMany(p => p.PlayerTeams)
                .HasForeignKey(d => d.TeamId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_player_teams_teams");
        });

        modelBuilder.Entity<PositionOverride>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__position__3213E83FD65B70D5");

            entity.ToTable("position_overrides");

            entity.HasIndex(e => e.FormationId, "IX_position_overrides_formation_id");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("id");
            entity.Property(e => e.Direction)
                .HasMaxLength(20)
                .HasColumnName("direction");
            entity.Property(e => e.FormationId).HasColumnName("formation_id");
            entity.Property(e => e.PositionIndex).HasColumnName("position_index");
            entity.Property(e => e.XCoord)
                .HasColumnType("decimal(5, 2)")
                .HasColumnName("x_coord");
            entity.Property(e => e.YCoord)
                .HasColumnType("decimal(5, 2)")
                .HasColumnName("y_coord");

            entity.HasOne(d => d.Formation).WithMany(p => p.PositionOverrides)
                .HasForeignKey(d => d.FormationId)
                .HasConstraintName("FK_position_overrides_formations");
        });

        modelBuilder.Entity<ProgressNote>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__progress__3213E83FB4C87CCE");

            entity.ToTable("progress_notes");

            entity.HasIndex(e => e.AddedBy, "IX_progress_notes_added_by");

            entity.HasIndex(e => e.PlanId, "IX_progress_notes_plan_id");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("id");
            entity.Property(e => e.AddedBy).HasColumnName("added_by");
            entity.Property(e => e.Note)
                .IsRequired()
                .HasColumnName("note");
            entity.Property(e => e.NoteDate)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnName("note_date");
            entity.Property(e => e.PlanId).HasColumnName("plan_id");

            entity.HasOne(d => d.AddedByNavigation).WithMany(p => p.ProgressNotes)
                .HasForeignKey(d => d.AddedBy)
                .HasConstraintName("FK_progress_notes_coaches");

            entity.HasOne(d => d.Plan).WithMany(p => p.ProgressNotes)
                .HasForeignKey(d => d.PlanId)
                .HasConstraintName("FK_progress_notes_plans");
        });

        modelBuilder.Entity<ReportDevelopmentAction>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__report_d__3213E83F0D6E4A10");

            entity.ToTable("report_development_actions");

            entity.HasIndex(e => e.ReportId, "IX_report_development_actions_report_id");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("id");
            entity.Property(e => e.Actions).HasColumnName("actions");
            entity.Property(e => e.Completed).HasColumnName("completed");
            entity.Property(e => e.CompletedDate).HasColumnName("completed_date");
            entity.Property(e => e.Goal)
                .IsRequired()
                .HasColumnName("goal");
            entity.Property(e => e.ReportId).HasColumnName("report_id");
            entity.Property(e => e.StartDate).HasColumnName("start_date");
            entity.Property(e => e.TargetDate).HasColumnName("target_date");

            entity.HasOne(d => d.Report).WithMany(p => p.ReportDevelopmentActions)
                .HasForeignKey(d => d.ReportId)
                .HasConstraintName("FK_report_development_actions_reports");
        });

        modelBuilder.Entity<SessionAttendance>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__session___3213E83FB6E0E51D");

            entity.ToTable("session_attendance");

            entity.HasIndex(e => e.PlayerId, "IX_session_attendance_player_id");

            entity.HasIndex(e => e.SessionId, "IX_session_attendance_session_id");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("id");
            entity.Property(e => e.Notes).HasColumnName("notes");
            entity.Property(e => e.PlayerId).HasColumnName("player_id");
            entity.Property(e => e.Present).HasColumnName("present");
            entity.Property(e => e.SessionId).HasColumnName("session_id");

            entity.HasOne(d => d.Player).WithMany(p => p.SessionAttendances)
                .HasForeignKey(d => d.PlayerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_session_attendance_players");

            entity.HasOne(d => d.Session).WithMany(p => p.SessionAttendances)
                .HasForeignKey(d => d.SessionId)
                .HasConstraintName("FK_session_attendance_sessions");
        });

        modelBuilder.Entity<SessionCoach>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__session___3213E83FAB871678");

            entity.ToTable("session_coaches");

            entity.HasIndex(e => e.CoachId, "IX_session_coaches_coach_id");

            entity.HasIndex(e => e.SessionId, "IX_session_coaches_session_id");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("id");
            entity.Property(e => e.CoachId).HasColumnName("coach_id");
            entity.Property(e => e.SessionId).HasColumnName("session_id");

            entity.HasOne(d => d.Coach).WithMany(p => p.SessionCoaches)
                .HasForeignKey(d => d.CoachId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_session_coaches_coaches");

            entity.HasOne(d => d.Session).WithMany(p => p.SessionCoaches)
                .HasForeignKey(d => d.SessionId)
                .HasConstraintName("FK_session_coaches_sessions");
        });

        modelBuilder.Entity<SessionDrill>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__session___3213E83FC1E0D20D");

            entity.ToTable("session_drills");

            entity.HasIndex(e => e.DrillId, "IX_session_drills_drill_id");

            entity.HasIndex(e => e.SessionId, "IX_session_drills_session_id");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("id");
            entity.Property(e => e.DrillId).HasColumnName("drill_id");
            entity.Property(e => e.DrillOrder).HasColumnName("drill_order");
            entity.Property(e => e.SessionId).HasColumnName("session_id");
            entity.Property(e => e.Source)
                .HasMaxLength(50)
                .HasColumnName("source");
            entity.Property(e => e.TemplateId).HasColumnName("template_id");

            entity.HasOne(d => d.Drill).WithMany(p => p.SessionDrills)
                .HasForeignKey(d => d.DrillId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_session_drills_drills");

            entity.HasOne(d => d.Session).WithMany(p => p.SessionDrills)
                .HasForeignKey(d => d.SessionId)
                .HasConstraintName("FK_session_drills_sessions");

            entity.HasOne(d => d.Template).WithMany(p => p.SessionDrills)
                .HasForeignKey(d => d.TemplateId)
                .HasConstraintName("FK_session_drills_templates");
        });

        modelBuilder.Entity<SimilarProfessional>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__similar___3213E83F9C531BD3");

            entity.ToTable("similar_professionals");

            entity.HasIndex(e => e.ReportId, "IX_similar_professionals_report_id");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("id");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("name");
            entity.Property(e => e.Position)
                .HasMaxLength(50)
                .HasColumnName("position");
            entity.Property(e => e.Reason).HasColumnName("reason");
            entity.Property(e => e.ReportId).HasColumnName("report_id");
            entity.Property(e => e.Team)
                .HasMaxLength(100)
                .HasColumnName("team");

            entity.HasOne(d => d.Report).WithMany(p => p.SimilarProfessionals)
                .HasForeignKey(d => d.ReportId)
                .HasConstraintName("FK_similar_professionals_reports");
        });

        modelBuilder.Entity<TacticPrinciple>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tactic_p__3213E83F145FEB01");

            entity.ToTable("tactic_principles");

            entity.HasIndex(e => e.FormationId, "IX_tactic_principles_formation_id");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("id");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.FormationId).HasColumnName("formation_id");
            entity.Property(e => e.PositionIndices).HasColumnName("position_indices");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("title");

            entity.HasOne(d => d.Formation).WithMany(p => p.TacticPrinciples)
                .HasForeignKey(d => d.FormationId)
                .HasConstraintName("FK_tactic_principles_formations");
        });

        modelBuilder.Entity<Team>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__teams__3213E83F97CC0D4C");

            entity.ToTable("teams");

            entity.HasIndex(e => e.AgeGroupId, "IX_teams_age_group_id");

            entity.HasIndex(e => e.ClubId, "IX_teams_club_id");

            entity.HasIndex(e => e.FormationId, "IX_teams_formation_id");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("id");
            entity.Property(e => e.AgeGroupId).HasColumnName("age_group_id");
            entity.Property(e => e.ClubId).HasColumnName("club_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnName("created_at");
            entity.Property(e => e.FormationId).HasColumnName("formation_id");
            entity.Property(e => e.IsArchived).HasColumnName("is_archived");
            entity.Property(e => e.Level)
                .HasMaxLength(50)
                .HasColumnName("level");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("name");
            entity.Property(e => e.PrimaryColor)
                .HasMaxLength(7)
                .HasColumnName("primary_color");
            entity.Property(e => e.Season)
                .HasMaxLength(20)
                .HasColumnName("season");
            entity.Property(e => e.SecondaryColor)
                .HasMaxLength(7)
                .HasColumnName("secondary_color");
            entity.Property(e => e.ShortName)
                .HasMaxLength(20)
                .HasColumnName("short_name");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnName("updated_at");

            entity.HasOne(d => d.AgeGroup).WithMany(p => p.Teams)
                .HasForeignKey(d => d.AgeGroupId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_teams_age_groups");

            entity.HasOne(d => d.Club).WithMany(p => p.Teams)
                .HasForeignKey(d => d.ClubId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_teams_clubs");

            entity.HasOne(d => d.Formation).WithMany(p => p.Teams)
                .HasForeignKey(d => d.FormationId)
                .HasConstraintName("FK_teams_formations");
        });

        modelBuilder.Entity<TeamCoach>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__team_coa__3213E83F5D7127B4");

            entity.ToTable("team_coaches");

            entity.HasIndex(e => e.CoachId, "IX_team_coaches_coach_id");

            entity.HasIndex(e => e.TeamId, "IX_team_coaches_team_id");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("id");
            entity.Property(e => e.AssignedAt)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnName("assigned_at");
            entity.Property(e => e.CoachId).HasColumnName("coach_id");
            entity.Property(e => e.TeamId).HasColumnName("team_id");

            entity.HasOne(d => d.Coach).WithMany(p => p.TeamCoaches)
                .HasForeignKey(d => d.CoachId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_team_coaches_coaches");

            entity.HasOne(d => d.Team).WithMany(p => p.TeamCoaches)
                .HasForeignKey(d => d.TeamId)
                .HasConstraintName("FK_team_coaches_teams");
        });

        modelBuilder.Entity<TemplateDrill>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__template__3213E83F5A169917");

            entity.ToTable("template_drills");

            entity.HasIndex(e => e.DrillId, "IX_template_drills_drill_id");

            entity.HasIndex(e => e.TemplateId, "IX_template_drills_template_id");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("id");
            entity.Property(e => e.DrillId).HasColumnName("drill_id");
            entity.Property(e => e.DrillOrder).HasColumnName("drill_order");
            entity.Property(e => e.TemplateId).HasColumnName("template_id");

            entity.HasOne(d => d.Drill).WithMany(p => p.TemplateDrills)
                .HasForeignKey(d => d.DrillId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_template_drills_drills");

            entity.HasOne(d => d.Template).WithMany(p => p.TemplateDrills)
                .HasForeignKey(d => d.TemplateId)
                .HasConstraintName("FK_template_drills_templates");
        });

        modelBuilder.Entity<TrainingObjective>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__training__3213E83F1375BECF");

            entity.ToTable("training_objectives");

            entity.HasIndex(e => e.PlanId, "IX_training_objectives_plan_id");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("id");
            entity.Property(e => e.Completed).HasColumnName("completed");
            entity.Property(e => e.CompletedDate).HasColumnName("completed_date");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.PlanId).HasColumnName("plan_id");
            entity.Property(e => e.Progress).HasColumnName("progress");
            entity.Property(e => e.StartDate).HasColumnName("start_date");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("status");
            entity.Property(e => e.TargetDate).HasColumnName("target_date");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("title");

            entity.HasOne(d => d.Plan).WithMany(p => p.TrainingObjectives)
                .HasForeignKey(d => d.PlanId)
                .HasConstraintName("FK_training_objectives_plans");
        });

        modelBuilder.Entity<TrainingPlan>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__training__3213E83FDE405B3C");

            entity.ToTable("training_plans");

            entity.HasIndex(e => e.CreatedBy, "IX_training_plans_created_by");

            entity.HasIndex(e => e.PlayerId, "IX_training_plans_player_id");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnName("created_at");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.PeriodEnd).HasColumnName("period_end");
            entity.Property(e => e.PeriodStart).HasColumnName("period_start");
            entity.Property(e => e.PlayerId).HasColumnName("player_id");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("status");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnName("updated_at");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.TrainingPlans)
                .HasForeignKey(d => d.CreatedBy)
                .HasConstraintName("FK_training_plans_coaches");

            entity.HasOne(d => d.Player).WithMany(p => p.TrainingPlans)
                .HasForeignKey(d => d.PlayerId)
                .HasConstraintName("FK_training_plans_players");
        });

        modelBuilder.Entity<TrainingSession>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__training__3213E83F33F3848E");

            entity.ToTable("training_sessions");

            entity.HasIndex(e => e.SessionDate, "IX_training_sessions_session_date");

            entity.HasIndex(e => e.TeamId, "IX_training_sessions_team_id");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnName("created_at");
            entity.Property(e => e.DurationMinutes).HasColumnName("duration_minutes");
            entity.Property(e => e.FocusAreas).HasColumnName("focus_areas");
            entity.Property(e => e.IsLocked).HasColumnName("is_locked");
            entity.Property(e => e.Location)
                .HasMaxLength(255)
                .HasColumnName("location");
            entity.Property(e => e.MeetTime).HasColumnName("meet_time");
            entity.Property(e => e.Notes).HasColumnName("notes");
            entity.Property(e => e.SessionDate).HasColumnName("session_date");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("status");
            entity.Property(e => e.TeamId).HasColumnName("team_id");
            entity.Property(e => e.TemplateId).HasColumnName("template_id");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnName("updated_at");

            entity.HasOne(d => d.Team).WithMany(p => p.TrainingSessions)
                .HasForeignKey(d => d.TeamId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_training_sessions_teams");

            entity.HasOne(d => d.Template).WithMany(p => p.TrainingSessions)
                .HasForeignKey(d => d.TemplateId)
                .HasConstraintName("FK_training_sessions_templates");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__users__3213E83FDA44DA32");

            entity.ToTable("users");

            entity.HasIndex(e => e.ClubId, "IX_users_club_id");

            entity.HasIndex(e => e.PlayerId, "IX_users_player_id");

            entity.HasIndex(e => e.StaffId, "IX_users_staff_id");

            entity.HasIndex(e => e.Email, "UQ__users__AB6E6164FA6B3287").IsUnique();

            entity.Property(e => e.Id)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("id");
            entity.Property(e => e.ClubId).HasColumnName("club_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnName("created_at");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("email");
            entity.Property(e => e.FirstName)
                .HasMaxLength(100)
                .HasColumnName("first_name");
            entity.Property(e => e.LastName)
                .HasMaxLength(100)
                .HasColumnName("last_name");
            entity.Property(e => e.Photo).HasColumnName("photo");
            entity.Property(e => e.PlayerId).HasColumnName("player_id");
            entity.Property(e => e.Preferences).HasColumnName("preferences");
            entity.Property(e => e.Role)
                .HasMaxLength(50)
                .HasColumnName("role");
            entity.Property(e => e.StaffId).HasColumnName("staff_id");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnName("updated_at");

            entity.HasOne(d => d.Club).WithMany(p => p.Users)
                .HasForeignKey(d => d.ClubId)
                .HasConstraintName("FK_users_clubs");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}