// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OurGame.Persistence.Models;

public partial class PerformanceRating
{
    public Guid Id { get; set; }

    public Guid MatchReportId { get; set; }

    public Guid PlayerId { get; set; }

    public decimal? Rating { get; set; }

    public virtual MatchReport MatchReport { get; set; }

    public virtual Player Player { get; set; }
}