// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OurGame.Persistence.Models;

public partial class PersonalSessionDrill
{
    public Guid Id { get; set; }

    public Guid PersonalSessionId { get; set; }

    public Guid DrillId { get; set; }

    public virtual Drill Drill { get; set; }

    public virtual PersonalSession PersonalSession { get; set; }
}