// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OurGame.Persistence.Models;

public partial class PlayerParent
{
    public Guid Id { get; set; }

    public Guid PlayerId { get; set; }

    public Guid ParentUserId { get; set; }

    public virtual User ParentUser { get; set; }

    public virtual Player Player { get; set; }
}