// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OurGame.Persistence.Models;

public partial class PlayerTeam
{
    public Guid Id { get; set; }

    public Guid PlayerId { get; set; }

    public Guid TeamId { get; set; }

    public int? SquadNumber { get; set; }

    public DateTime AssignedAt { get; set; }

    public virtual Player Player { get; set; }

    public virtual Team Team { get; set; }
}