// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OurGame.Persistence.Models;

public partial class SessionAttendance
{
    public Guid Id { get; set; }

    public Guid SessionId { get; set; }

    public Guid PlayerId { get; set; }

    public bool Present { get; set; }

    public string Notes { get; set; }

    public virtual Player Player { get; set; }

    public virtual TrainingSession Session { get; set; }
}