// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OurGame.Persistence.Models;

public partial class SimilarProfessional
{
    public Guid Id { get; set; }

    public Guid ReportId { get; set; }

    public string Name { get; set; }

    public string Team { get; set; }

    public string Position { get; set; }

    public string Reason { get; set; }

    public virtual PlayerReport Report { get; set; }
}