// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OurGame.Persistence.Models;

public partial class TemplateDrill
{
    public Guid Id { get; set; }

    public Guid TemplateId { get; set; }

    public Guid DrillId { get; set; }

    public int DrillOrder { get; set; }

    public virtual Drill Drill { get; set; }

    public virtual DrillTemplate Template { get; set; }
}