// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OurGame.Persistence.Models;

public partial class TrainingObjective
{
    public Guid Id { get; set; }

    public Guid PlanId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public DateOnly? StartDate { get; set; }

    public DateOnly? TargetDate { get; set; }

    public string Status { get; set; }

    public int? Progress { get; set; }

    public bool Completed { get; set; }

    public DateOnly? CompletedDate { get; set; }

    public virtual TrainingPlan Plan { get; set; }
}