// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OurGame.Persistence.Models;

public partial class TrainingSession
{
    public Guid Id { get; set; }

    public Guid TeamId { get; set; }

    public DateTime SessionDate { get; set; }

    public DateTime? MeetTime { get; set; }

    public int? DurationMinutes { get; set; }

    public string Location { get; set; }

    public string FocusAreas { get; set; }

    public Guid? TemplateId { get; set; }

    public string Notes { get; set; }

    public string Status { get; set; }

    public bool IsLocked { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ICollection<AppliedTemplate> AppliedTemplates { get; set; } = new List<AppliedTemplate>();

    public virtual ICollection<SessionAttendance> SessionAttendances { get; set; } = new List<SessionAttendance>();

    public virtual ICollection<SessionCoach> SessionCoaches { get; set; } = new List<SessionCoach>();

    public virtual ICollection<SessionDrill> SessionDrills { get; set; } = new List<SessionDrill>();

    public virtual Team Team { get; set; }

    public virtual DrillTemplate Template { get; set; }
}